fix: type assertion in cache-management test using unknown (#1482)
fixes build error:

```
│ src/lib/cache-management.spec.ts(90,4): error TS2352: Conversion of type '{ name: string; isDirectory: () => false; }…
│   Type '{ name: string; isDirectory: () => false; }' is missing the following properties from type 'Dirent<Buffer<Arr…
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 1.6s at /Users/mishig/huggingface.js/packages/hub
```